=== Jaicomp/Activity-Shop/xml/activities.dtd
<!ELEMENT activities (activity)>
<!ELEMENT activity (id, creator_id, title, date, price, capacity, location, duration, description, imgurl)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT creator_id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT capacity (current, maximum)>
<!ELEMENT current (#PCDATA)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT location (latitude, longitude)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT imgurl (#PCDATA)>

=== Jaicomp/Activity-Shop/xml/activities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE activities SYSTEM "activities.dtd">
<activities>
  <activity>
    <id>1</id>
    <creator_id>1</creator_id>
    <title>Excursion Tramuntana</title>
    <date>01/01/2017</date>
    <price>30</price>
    <capacity>
      <current>10</current>
      <maximum>20</maximum>
    </capacity>
    <location>
      <latitude>1234</latitude>
      <longitude>1234</longitude>
    </location>
    <duration></duration>
    <description></description>
    <imgurl></imgurl>
  </activity>
  <activity>
    <id>2</id>
    <creator_id>2</creator_id>
    <title>Basketball Competition</title>
    <date>01/01/2017</date>
    <price>30</price>
    <capacity>
      <current>10</current>
      <maximum>20</maximum>
    </capacity>
    <location>
      <latitude>1234</latitude>
      <longitude>1234</longitude>
    </location>
    <duration></duration>
    <description></description>
    <imgurl></imgurl>
  </activity>
</activities>
