=== Jaicomp/Activity-Shop/xml/groups.dtd
<!ELEMENT groups(group)>
<!ELEMENT group (id, name, creator_id, collaborators_id, users_id, description, activity_list, url_icon, date_creation)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT creator_id (#PCDATA)>
<!ELEMENT collaborators_id (id)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT users_id (id)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT activity_list (id)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT url_icon (#PCDATA)>
<!ELEMENT date_creation (#PCDATA)>

=== Jaicomp/Activity-Shop/xml/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "groups.dtd">
<groups>
	<group id = "1">
		<name>Group 1</name>
		<creator_id>1</creator_id>
		<organizer_id type="array">
			<id>1</id>
			<id>2</id>
		</organizer_id>

		<users_id>
			<id>3</id>
			<id>4<id>
		</users_id>

		<description></description>

		<activity_list>
			<id>1</id>
			<id>2</id>
		<activity_list>
			
		<url_icon></url_icon>

		<hashtag>#losmasguays</hashtag>

		<date_creation>01/01/2017</date_creation>
	</group>


</groups>
